# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/AppWindow.ui'
#
# Created: Fri Nov  5 10:51:10 2010
#      by: PyQt4 UI code generator 4.7.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_AppWindow(object):
    def setupUi(self, AppWindow):
        AppWindow.setObjectName("AppWindow")
        AppWindow.resize(558, 446)
        self.centralwidget = QtGui.QWidget(AppWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setMargin(2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.splitter = QtGui.QSplitter(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitter.sizePolicy().hasHeightForWidth())
        self.splitter.setSizePolicy(sizePolicy)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.resultView = QtGui.QTableView(self.splitter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.resultView.sizePolicy().hasHeightForWidth())
        self.resultView.setSizePolicy(sizePolicy)
        self.resultView.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.resultView.setAlternatingRowColors(True)
        self.resultView.setHorizontalScrollMode(QtGui.QAbstractItemView.ScrollPerPixel)
        self.resultView.setObjectName("resultView")
        self.entryBox = QtGui.QPlainTextEdit(self.splitter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.entryBox.sizePolicy().hasHeightForWidth())
        self.entryBox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Andale Mono")
        self.entryBox.setFont(font)
        self.entryBox.setObjectName("entryBox")
        self.verticalLayout_2.addWidget(self.splitter)
        AppWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(AppWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 558, 23))
        self.menubar.setObjectName("menubar")
        self.menu_File = QtGui.QMenu(self.menubar)
        self.menu_File.setObjectName("menu_File")
        self.menu_SQL = QtGui.QMenu(self.menubar)
        self.menu_SQL.setObjectName("menu_SQL")
        self.menu_Python = QtGui.QMenu(self.menubar)
        self.menu_Python.setObjectName("menu_Python")
        self.menu_Edit = QtGui.QMenu(self.menubar)
        self.menu_Edit.setObjectName("menu_Edit")
        self.menuView = QtGui.QMenu(self.menubar)
        self.menuView.setObjectName("menuView")
        AppWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(AppWindow)
        self.statusbar.setObjectName("statusbar")
        AppWindow.setStatusBar(self.statusbar)
        self.action_Quit = QtGui.QAction(AppWindow)
        self.action_Quit.setObjectName("action_Quit")
        self.action_Execute = QtGui.QAction(AppWindow)
        self.action_Execute.setObjectName("action_Execute")
        self.action_PyExecute = QtGui.QAction(AppWindow)
        self.action_PyExecute.setObjectName("action_PyExecute")
        self.action_Clone = QtGui.QAction(AppWindow)
        self.action_Clone.setObjectName("action_Clone")
        self.action_InteractiveMode = QtGui.QAction(AppWindow)
        self.action_InteractiveMode.setCheckable(True)
        self.action_InteractiveMode.setObjectName("action_InteractiveMode")
        self.action_PreviousQuery = QtGui.QAction(AppWindow)
        self.action_PreviousQuery.setObjectName("action_PreviousQuery")
        self.action_NextQuery = QtGui.QAction(AppWindow)
        self.action_NextQuery.setObjectName("action_NextQuery")
        self.action_NextResultset = QtGui.QAction(AppWindow)
        self.action_NextResultset.setObjectName("action_NextResultset")
        self.action_Open = QtGui.QAction(AppWindow)
        self.action_Open.setObjectName("action_Open")
        self.action_Copy = QtGui.QAction(AppWindow)
        self.action_Copy.setObjectName("action_Copy")
        self.action_Cut = QtGui.QAction(AppWindow)
        self.action_Cut.setObjectName("action_Cut")
        self.action_Paste = QtGui.QAction(AppWindow)
        self.action_Paste.setObjectName("action_Paste")
        self.action_Panel = QtGui.QAction(AppWindow)
        self.action_Panel.setCheckable(True)
        self.action_Panel.setObjectName("action_Panel")
        self.action_Reconnect = QtGui.QAction(AppWindow)
        self.action_Reconnect.setObjectName("action_Reconnect")
        self.action_FocusResults = QtGui.QAction(AppWindow)
        self.action_FocusResults.setObjectName("action_FocusResults")
        self.action_FocusEntry = QtGui.QAction(AppWindow)
        self.action_FocusEntry.setObjectName("action_FocusEntry")
        self.menu_File.addAction(self.action_Clone)
        self.menu_File.addAction(self.action_Open)
        self.menu_File.addSeparator()
        self.menu_File.addAction(self.action_Quit)
        self.menu_File.addAction(self.action_Reconnect)
        self.menu_SQL.addAction(self.action_Execute)
        self.menu_SQL.addSeparator()
        self.menu_SQL.addAction(self.action_PreviousQuery)
        self.menu_SQL.addAction(self.action_NextQuery)
        self.menu_SQL.addAction(self.action_NextResultset)
        self.menu_SQL.addSeparator()
        self.menu_SQL.addAction(self.action_InteractiveMode)
        self.menu_Python.addAction(self.action_PyExecute)
        self.menu_Edit.addAction(self.action_Cut)
        self.menu_Edit.addAction(self.action_Copy)
        self.menu_Edit.addAction(self.action_Paste)
        self.menu_Edit.addSeparator()
        self.menu_Edit.addAction(self.action_FocusResults)
        self.menu_Edit.addAction(self.action_FocusEntry)
        self.menuView.addAction(self.action_Panel)
        self.menubar.addAction(self.menu_File.menuAction())
        self.menubar.addAction(self.menu_Edit.menuAction())
        self.menubar.addAction(self.menu_SQL.menuAction())
        self.menubar.addAction(self.menu_Python.menuAction())
        self.menubar.addAction(self.menuView.menuAction())

        self.retranslateUi(AppWindow)
        QtCore.QObject.connect(self.action_FocusEntry, QtCore.SIGNAL("activated()"), self.entryBox.setFocus)
        QtCore.QObject.connect(self.action_FocusResults, QtCore.SIGNAL("activated()"), self.resultView.setFocus)
        QtCore.QObject.connect(self.action_Quit, QtCore.SIGNAL("activated()"), AppWindow.close)
        QtCore.QMetaObject.connectSlotsByName(AppWindow)

    def retranslateUi(self, AppWindow):
        AppWindow.setWindowTitle(QtGui.QApplication.translate("AppWindow", "Syleqt", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_File.setTitle(QtGui.QApplication.translate("AppWindow", "Connec&tion", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_SQL.setTitle(QtGui.QApplication.translate("AppWindow", "&SQL", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_Python.setTitle(QtGui.QApplication.translate("AppWindow", "Scri&pt", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_Edit.setTitle(QtGui.QApplication.translate("AppWindow", "&Edit", None, QtGui.QApplication.UnicodeUTF8))
        self.menuView.setTitle(QtGui.QApplication.translate("AppWindow", "Vie&w", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Quit.setText(QtGui.QApplication.translate("AppWindow", "&Quit", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Quit.setShortcut(QtGui.QApplication.translate("AppWindow", "Ctrl+Q", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Execute.setText(QtGui.QApplication.translate("AppWindow", "&Execute", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Execute.setShortcut(QtGui.QApplication.translate("AppWindow", "Ctrl+Return", None, QtGui.QApplication.UnicodeUTF8))
        self.action_PyExecute.setText(QtGui.QApplication.translate("AppWindow", "&Run", None, QtGui.QApplication.UnicodeUTF8))
        self.action_PyExecute.setShortcut(QtGui.QApplication.translate("AppWindow", "Ctrl+Shift+Return", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Clone.setText(QtGui.QApplication.translate("AppWindow", "Clo&ne", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Clone.setShortcut(QtGui.QApplication.translate("AppWindow", "Alt+N", None, QtGui.QApplication.UnicodeUTF8))
        self.action_InteractiveMode.setText(QtGui.QApplication.translate("AppWindow", "&Interactive Mode", None, QtGui.QApplication.UnicodeUTF8))
        self.action_InteractiveMode.setShortcut(QtGui.QApplication.translate("AppWindow", "Alt+I", None, QtGui.QApplication.UnicodeUTF8))
        self.action_PreviousQuery.setText(QtGui.QApplication.translate("AppWindow", "&Previous Query", None, QtGui.QApplication.UnicodeUTF8))
        self.action_PreviousQuery.setShortcut(QtGui.QApplication.translate("AppWindow", "Ctrl+Up", None, QtGui.QApplication.UnicodeUTF8))
        self.action_NextQuery.setText(QtGui.QApplication.translate("AppWindow", "&Next Query", None, QtGui.QApplication.UnicodeUTF8))
        self.action_NextQuery.setShortcut(QtGui.QApplication.translate("AppWindow", "Ctrl+Down", None, QtGui.QApplication.UnicodeUTF8))
        self.action_NextResultset.setText(QtGui.QApplication.translate("AppWindow", "Next Resultset", None, QtGui.QApplication.UnicodeUTF8))
        self.action_NextResultset.setShortcut(QtGui.QApplication.translate("AppWindow", "Alt+Return", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Open.setText(QtGui.QApplication.translate("AppWindow", "&Open...", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Open.setShortcut(QtGui.QApplication.translate("AppWindow", "Alt+O", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Copy.setText(QtGui.QApplication.translate("AppWindow", "&Copy", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Copy.setShortcut(QtGui.QApplication.translate("AppWindow", "Alt+C", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Cut.setText(QtGui.QApplication.translate("AppWindow", "Cu&t", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Cut.setShortcut(QtGui.QApplication.translate("AppWindow", "Alt+X", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Paste.setText(QtGui.QApplication.translate("AppWindow", "&Paste", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Paste.setShortcut(QtGui.QApplication.translate("AppWindow", "Alt+V", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Panel.setText(QtGui.QApplication.translate("AppWindow", "&Panel", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Panel.setShortcut(QtGui.QApplication.translate("AppWindow", "F4", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Reconnect.setText(QtGui.QApplication.translate("AppWindow", "&Reconnect", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Reconnect.setShortcut(QtGui.QApplication.translate("AppWindow", "Alt+R", None, QtGui.QApplication.UnicodeUTF8))
        self.action_FocusResults.setText(QtGui.QApplication.translate("AppWindow", "Focus Results", None, QtGui.QApplication.UnicodeUTF8))
        self.action_FocusResults.setShortcut(QtGui.QApplication.translate("AppWindow", "Ctrl+PgUp", None, QtGui.QApplication.UnicodeUTF8))
        self.action_FocusEntry.setText(QtGui.QApplication.translate("AppWindow", "Focus Entry", None, QtGui.QApplication.UnicodeUTF8))
        self.action_FocusEntry.setShortcut(QtGui.QApplication.translate("AppWindow", "Ctrl+PgDown", None, QtGui.QApplication.UnicodeUTF8))

